version: "3.6"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: wavy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wavy
      PGPASSWORD: root
    ports:
      - 5432:5432

  app:
    image: node:16
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://wavy:password@db:5432/wavy
    command: npm run dev

  prisma-studio:
    image: node:16
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgresql://wavy:password@db:5432/wavy
    command: npx prisma studio
